name: "Build: Bare Metal"

on:
  push:
    branches: [main]
    paths:
      - bare-metal/**
      - .github/actions/install-toolchain/**
      - .github/workflows/build-bare-metal.yml
  pull_request:
    paths:
      - bare-metal/**
      - .github/actions/install-toolchain/**
      - .github/workflows/build-bare-metal.yml

jobs:
  bare-metal:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 1
      - uses: ./.github/actions/install-toolchain
      - name: Build and test bare-metal
        run: make -C bare-metal test
