name: "Build: FreeRTOS"

on:
  push:
    branches: [main]
    paths:
      - freertos/**
      - .github/actions/install-toolchain/**
      - .github/workflows/build-freertos.yml
  pull_request:
    paths:
      - freertos/**
      - .github/actions/install-toolchain/**
      - .github/workflows/build-freertos.yml

jobs:
  freertos:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 1
      - uses: ./.github/actions/install-toolchain
      - name: Build and test freertos
        run: make -C freertos test
